config/routes.rb
Manga4koma::Application.routes.draw do
	match "/about", :to => "pages#about"
	match "/help", :to => "pages#help"
	match "/contact", :to => "pages#contact"
	match "/developer", :to => "pages#developer"

	resources :pictures
	resources :chapters
	resources :komas
	resources :layers

  resources :mangas do
  	resources :chapters do
  		resources :komas do
  			resources :layers
  		end
  	end
  end

	devise_for :users
	resources :users, :only => [:show, :index] do
		member do
			get :followers, :following, :stalkers, :stalking
		end
	end

  root :to => "pages#home"

end

app/models/manga.rb
# == Schema Information
#
# Table name: mangas
#
#  id         :integer(4)      not null, primary key
#  user_id    :integer(4)
#  title      :string(255)
#  summary    :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Manga < ActiveRecord::Base
	has_many :chapters
	has_many :collaboration, :foreign_key => :manga_id, :dependent => :destroy
	has_many :collaborators, :through => :collaboration, :source =>  :collaborator
	belongs_to :user
end

app/controllers/mangas_controller.rb
class MangasController < ApplicationController

	# GET request
	def index
		@title = "Manga List"
		@mangas = Manga.paginate( :page => params[:page] )
	end
	
	# GET request
	def new
		if user_signed_in?
			@manga = current_user.mangas.new
		else
			
		end
	end
	
	# POST request
	def create
		@manga = current_user.mangas.build( params[:manga] )
		if @manga.save
			flash[:success] = "Manga successfully created!"
			redirect_to current_user
		else
			flash[:error] = "Failed to create manga..."
			redirect_to root_path
		end
	end
	
	# GET request
	def show
		@manga = Manga.find_by_id(params[:id])	
		
	end
	
	# PUT request
	def update
	
	end
	
	# GET request
	def edit
	
	end
	
	# DELETE request
	def destroy
	
	end
	
end

app/helpers/mangas_helper.rb
module MangasHelper
end

app/views/mangas/edit.html.erb
<h1>Mangas#edit</h1>
<p>Find me in app/views/mangas/edit.html.erb</p>

app/views/mangas/index.html.erb
<div class="hero-unit">
	<h1>Manga Index!</h1>
	<p>Check out the works of others or make your own!</p>
	<p><%= link_to "Create new manga »", new_manga_path, :class => "btn primary large" %></p>
</div>
<%= will_paginate @mangas %>

	<% @mangas.each do |manga| %>
	<div class="row">
		<h3><%= link_to manga.title, manga %></h3>
		<p>Manga summary goes here</p>
	</div>
	<% end %>

<%= will_paginate @mangas %>

app/views/mangas/new.html.erb
<div class="hero-unit">
	<% if user_signed_in? %>
		<h1>Create a new manga!</h1>
		<% form_for @manga, :html => { :multipart => true } do |f| %>
			<p><%= f.label :title %></p>
			<p><%= f.text_field :title %></p>
			<p><%= f.label :summary %></p>
			<p><%= f.text_area :summary %></p>
			<p><%= f.submit :submit %></p>
		<% end %>
	<% else %>
		<h1>Please sign in first buddy!</h1>
	<% end %>
</div>

app/views/mangas/show.html.erb
<div class="hero-unit">
	<h1><%= @manga.title %></h1>
	<h3>by <%= @manga.user_id %></h3>
	<p><%= @manga.summary %></p>
	<p><%= link_to "Reading List »", "#", :class => "btn primary large" %></p>
</div>

<div class="row">
<% if @manga.chapters.empty? %>
	<h2>Nothing here yet! You should consider making a new chapter !</h2>
<% else %>
	<% @manga.chapters.each do |chapter| %>
		<div class="row">
			<h3><%= link_to "Chapter #{chapter.chapter_number}: #{chapter.title}", manga_path(@manga) + chapter_path(chapter) %></h3>
			<p>Updated at: <%= chapter.updated_at %></p>
		</div>
	<% end %>
<% end %>
<h3><%= link_to "Add New Chapter »", manga_path(@manga) + new_chapter_path, :class => "btn large" %></h3>
</div>