config/routes.rb
Manga4koma::Application.routes.draw do
	match "/about", :to => "pages#about"
	match "/help", :to => "pages#help"
	match "/contact", :to => "pages#contact"
	match "/developer", :to => "pages#developer"

	resources :pictures
	resources :chapters
	resources :komas
	resources :layers

  resources :mangas do
  	resources :chapters do
  		resources :komas do
  			resources :layers
  		end
  	end
  end

	devise_for :users
	resources :users, :only => [:show, :index] do
		member do
			get :followers, :following, :stalkers, :stalking
		end
	end

  root :to => "pages#home"

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer(4)      not null, primary key
#  email                  :string(255)     default(""), not null
#  encrypted_password     :string(128)     default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer(4)      default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  name                   :string(255)
#  user_level             :integer(4)      default(0)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	# Validations
	validates :name, :email, :presence => true, :uniqueness => { :case_sensitive => false }
	validates :email, :format => { :with => /[a-zA-Z0-9\-_\."]{1,}@[a-zA-Z0-9\-_]{1,}\.[a-zA-Z0-9]{1,}/ }
	validates :password, :confirmation => true

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
  # Data model for having manga
  has_many :mangas
  has_many :pictures
  
  # Data model for relationships and obsessions
  has_many :relationships, :foreign_key => "follower_id", :dependent => :destroy
  has_many :reverse_relationships, :foreign_key => "followed_id", :class_name => "Relationship", :dependent => :destroy
  has_many :obsessions, :foreign_key => "stalker_id", :dependent => :destroy
  has_many :reverse_obsessions, :foreign_key => "stalked_id", :class_name => "Obsession", :dependent => :destroy
  has_many :following, :through => :relationships, :source => :followed
  has_many :followers, :through => :reverse_relationships, :source => :follower
  has_many :stalking, :through => :obsessions, :source => :stalked
  has_many :stalkers, :through => :reverse_obsessions, :source => :stalker
  
  # Some helper functions to deal with the above relationships
  def following?(followed)
  	relationships.find_by_followed_id(followed)
  end
  
  def follow!(followed)
  	relationships.create!( :followed_id => followed )
  end
  
  def unfollow(followed)
  	relationships.find_by_followed_id(followed).destroy
  end
  
  def stalking?(stalked)
  	obsessions.find_by_stalked_id(stalked)
  end
  
  def stalk!(stalked)
  	obsessions.create!(:stalked_id => stalked)
  end
  
  def unstalk(stalked)
  	obsessions.find_by_stalked_id(stalked).destroy
  end
  
  # Administrative functions; should only be used by admin users
  def alter_user_level(user_level)
  	self.user_level = user_level
  	self.save
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find_by_id(params[:id])
	@correct_user = ( current_user.id == @user.id ) if user_signed_in?
	if @correct_user
		@picture = current_user.pictures.new
	end
  end

  def index
  # IMPLEMENT ME!!
  end
  
  def following
  	@title = "Following"
  	@user = User.find(params[:id])
  	@users = @user.following.paginate(:page => params[:page])
  	@correct_user = user_signed_in? ? current_user.id == @user.id : false
  	render "show_follow"
  end
  
  def followers
  	@title = "Followers"
  	@user = User.find(params[:id])
  	@users = @user.followers.paginate(:page => params[:page])
  	@correct_user = user_signed_in? ? current_user.id == @user.id : false
  	render "show_follow"
  end
  
  def stalking
  	@title = "Stalking"
  	@user = User.find(params[:id])
  	@users = @user.stalking.paginate(:page => params[:page])
  	@correct_user = user_signed_in? ? current_user.id == @user.id : false
  	render "show_stalk"
  end
  
  def stalkers
  	@title = "Stalkers"
  	@user = User.find(params[:id])
  	@users = @user.stalkers.paginate(:page => params[:page])
  	@correct_user = user_signed_in? ? current_user.id == @user.id : false  	
  	render "show_stalk"  	
  end

end

app/helpers/users_helper.rb
module UsersHelper
	def authenticate
		deny_access unless user_signed_in?
	end
	
	def deny_access
		redirect_to new_user_session_path, :notice => "You need to be signed in to do that"
	end
end

app/views/users/_stats.html.erb
<ul style="list-style: none; display: inline-block;">
	<li><%= link_to "Following: ", following_user_path(user) %><%= user.following.count %></li>
	<li><%= link_to "Followers: ", followers_user_path(user) %><%= user.followers.count %></li>
	<% if current_user.id == user.id %>
		<li><%= link_to "Stalking: ", stalking_user_path(user) %><%= user.stalking.count %></li>
	<% else %>
		<li>Stalking: ??</li>
	<% end %>
	<li>Stalkers: <%= user.stalkers.count %></li>
</ul>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<div class="hero-unit">
<% if @correct_user %>
	<h1>My Dashboard</h1>
	<p>[Minifeed not implemented yet]</p>
<% else %>
	<h1><%= @user.name %></h1>
	<p>Check out what this faggot is doing!</p>
	<% if user_signed_in? %>
		<% unless current_user.following?(@user) %>
			<%= form_for current_user.relationships.build(:followed_id => @user.id), :remote => true do |f| %>
				<%= f.hidden_field :followed_id %>
				<%= f.submit "Follow »", :class => "btn primary" %>
			<% end %>
		<% else %>
			<%= form_for current_user.relationships.find_by_followed_id(@user), :html => { :method => :delete }, :remote => true do |f| %>
				<%= f.submit "Unfollow »", :class => "btn" %>
			<% end %>
		<% end %>
		<% unless current_user.stalking?(@user) %>
			<%= form_for current_user.obsessions.build(:stalked_id => @user.id), :remote => true do |f| %>
				<%= f.hidden_field :stalked_id %>
				<%= f.submit "Stalk »", :class => "btn primary" %>
			<% end %>
		<% else %>
			<%= form_for current_user.obsessions.find_by_stalked_id(@user), :html => { :method => :delete }, :remote => true do |f| %>
				<%= f.submit "Unstalk »", :class => "btn" %>
			<% end %>
		<% end %>
	<% end %>
<% end %>
	<%= render "users/stats", :user => @user %>
</div>

<div class="row">
	<div class="span-one-third">
		<% if @correct_user %>
			<h3>My Manga</h3>
			<p><%= link_to "New Manga »", new_manga_path, :class => "btn" %></p>
		<% else %>
			<h3>This faggot's mangas</h3>
		<% end %>
		<ul>
			<% @user.mangas.each do |manga| %>
				<li><%= link_to manga.title, manga_path(manga) %></li>
			<% end %>
		</ul>
	</div>
	<div class="span-one-third">
		<% if @correct_user %>
			<h3>My Stock</h3>
			<p>Remember: PNGs only!!</p>
			<% form_for  @picture, :html => { :multipart => true } do |f| %>
				<%= f.file_field :pic %>
				<%= f.submit "New picture »" %> 
			<% end %>
		<% else %>
			<h3>This faggot's pictures</h3>
		<% end %>
		<ul>
		<% @user.pictures.each do |picture| %>
			<li><%= image_tag picture.pic.url, :size => "150x150" %></li>
		<% end %>
		</ul>
	</div>
	<div class="span-one-third">
		<% if @correct_user %>
			<h3>My activities</h3>
		<% else %>
			<h3>This faggot's activities</h3>
		<% end %>
		<p>[Not implemented yet!!]</p>
	</div>
</div>

app/views/users/show_follow.html.erb
<div class="hero-unit">
	<h2><%= "#{@user.name}'s #{@title}" %></h2>
	<p>You have <%= @users.count %> people in your <%= @title %> group!</p>
</div>

<div class="row">
	<ul>
	<%= will_paginate @users %>
	<% @users.each do |user| %>
		<li>
			<%= link_to user.name, user %>
			<% if @correct_user && @title == "Following" %>
				<%= form_for current_user.relationships.find_by_followed_id(@user), :html => { :method => :delete }, :remote => true do |f| %>
					<%= f.submit "Unfollow »", :class => "btn" %>
				<% end %>
			<% end %>
		</li>
	<% end %>
	<%= will_paginate @users %>
	</ul>
</div>

app/views/users/show_stalk.html.erb
<div class="hero-unit">
	<h1><%= @title %></h1>
	<% if @title == "Stalking" %>
		<% if @correct_user %>
			<p>You are stalking <%= pluralize( @users.count, "person") %></p>
		<% else %>
			<p><%= @user.name %> is stalking some (possibly 0) number of users</p>
		<% end %>
	<% else  %>
		<p><%= @user.name %> has <%= pluralize(@users.count, "stalker") %></p>
	<% end %>
</div>

<div class="row">
	<ul>
	<% if @correct_user && @title == "Stalking" %>
	<%= will_paginate @users %>
	<% @users.each do |user| %>
		<li>
			<%= link_to user.name, user %>
			<%= form_for current_user.obsessions.find_by_stalked_id(user), :html => { :method => :delete }, :remote => true do |f| %>
				<%= f.submit "Unstalk »", :class => "btn" %>
			<% end %>
		</li>
	<% end %>
	<%= will_paginate @users %>
	<% else %>
		<p>Sorry buddy, your stalkers (if you have any) are too good at avoiding detection.</p>
	<% end %>	
	</ul>
</div>