config/routes.rb
Manga4koma::Application.routes.draw do
	match "/about", :to => "pages#about"
	match "/help", :to => "pages#help"
	match "/contact", :to => "pages#contact"
	match "/developer", :to => "pages#developer"

	resources :pictures
	resources :chapters
	resources :komas
	resources :layers

  resources :mangas do
  	resources :chapters do
  		resources :komas do
  			resources :layers
  		end
  	end
  end

	devise_for :users
	resources :users, :only => [:show, :index] do
		member do
			get :followers, :following, :stalkers, :stalking
		end
	end

  root :to => "pages#home"

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" >
    <h2><%= pluralize(object.errors.count, "error") %>
      prohibited this <%= object.class.to_s.underscore.humanize.downcase %> from being saved:</h2>
    <p>There were problems with the following fields</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
<p>
	&copy; 4koma 2011 |
	<%= link_to "Home", "/" %> |
	<%= link_to "About", "/about" %> |
	<%= link_to "Help", "/help" %> |
	<%= link_to "Contact", "/contact" %> |
	<%= link_to "Developer", "/developer" %>
</p>
</footer>

app/views/shared/_header.html.erb
<header>
<nav>
<div class="topbar">
  <div class="fill">
    <div class="container">
      <a class="brand" href="/">4koma</a>
      <ul class="nav">
        <li class="active"><%= link_to "Home", "/" %></li>
        <li><%= link_to "Manga List", mangas_path %></li>
        <li><%= link_to "Showcase", "#" %></li>
        <% if user_signed_in? %>
			<li><%= link_to "My Dashboard", current_user %></li>
			<li><%= link_to "Logout", destroy_user_session_path, :method => :delete %>
		<% else %>
			<li><%= link_to "Sign in", new_user_session_path %></li>
			<li><%= link_to "Sign up", new_user_registration_path %></li>
		<% end %>
      </ul>
    </div>
  </div>
</div>
</nav>
</header>