config/routes.rb
Manga4koma::Application.routes.draw do
	match "/about", :to => "pages#about"
	match "/help", :to => "pages#help"
	match "/contact", :to => "pages#contact"
	match "/developer", :to => "pages#developer"

	resources :pictures
	resources :chapters
	resources :komas
	resources :layers

  resources :mangas do
  	resources :chapters do
  		resources :komas do
  			resources :layers
  		end
  	end
  end

	devise_for :users
	resources :users, :only => [:show, :index] do
		member do
			get :followers, :following, :stalkers, :stalking
		end
	end

  root :to => "pages#home"

end

app/models/chapter.rb
# == Schema Information
#
# Table name: chapters
#
#  id             :integer(4)      not null, primary key
#  manga_id       :integer(4)
#  title          :string(255)
#  chapter_number :integer(4)
#  chapter_before :integer(4)
#  chapter_after  :integer(4)
#  created_at     :datetime
#  updated_at     :datetime
#

class Chapter < ActiveRecord::Base
	has_many :komas
	belongs_to :manga
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController

	# GET request
	def new
		@manga = Manga.find_by_id(params[:manga_id])
		@chapter = @manga.chapters.new
	end
	
	# POST request
	def create
		@manga = Manga.find_by_id(params[:manga_id])
		@chapter = @manga.chapters.build(params[:chapter])
		if @chapter.save
			flash[:success] = "New chapter successfully created!"
			redirect_to( manga_path(@manga) + chapter_path(@chapter))
		else
			flash[:error] = "Failed to create new chapter"
			redirect_to manga_path(@manga)
		end
	end
	
	# GET request
	def show
		# Normal people should just be content to read the manga
		@manga = Manga.find_by_id(params[:manga_id])
		@chapter = @manga.chapters.find_by_id(params[:id])
		@komas = @chapter.komas.paginate( :page => params[:page] )
		
		# Collaborators and owners can add new content
		@correct_user = @manga.collaborators.find_by_id(current_user.id).nil? ? true : false
		@correct_user = @manga.user.id == current_user.id		
	end
	
	def edit
	
	end
	
	def destroy
	
	end
	
	
	
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/chapters/edit.html.erb
<h1>Chapters#edit</h1>
<p>Find me in app/views/chapters/edit.html.erb</p>

app/views/chapters/index.html.erb
<h1>Chapters#index</h1>
<p>Find me in app/views/chapters/index.html.erb</p>

app/views/chapters/new.html.erb
<div class="hero-unit">
	<% if user_signed_in? %>
		<h3><%= "New Chapter for #{@manga.title}" %></h3>
		<% form_for( [@manga, @chapter], :html => { :multipart => true } ) do |f| %>
			<p><%= f.label :title %>
			<%= f.text_field :title %></p>
			<p><%= f.label :chapter_number %>
			<%= f.text_field :chapter_number %></p>
			<p><%= f.submit :submit %></p>
		<% end %>
	<% else %>
		<h1>Please sign in first buddy!</h1>
		<p><%= link_to "Sign In »", signin_path, :class => "btn primary large" %></p>
	<% end %>
</div>

app/views/chapters/show.html.erb
<div class="hero-unit">
<h3><%= @chapter.title %></h3>
<p><%= "Chapter #{@chapter.chapter_number} of " %><%= link_to @manga.title, manga_path(@manga) %></p>
<% if @correct_user %>
	<%= link_to "Add Another Koma »", manga_path(@manga) + chapter_path(@chapter) + new_koma_path, :class => "btn primary large" %>	
<% end %>
</div>
<%= will_paginate @komas %>
<% @komas.each do |koma| %>
<div class="row">
	<%= link_to "Edit koma »", manga_path(@manga) + chapter_path(@chapter) + koma_path(koma), :class => "btn" %>
	<%= render koma, :koma => koma %>
</div>
<% end %>
<%= will_paginate @komas %>